<a href="https://colab.research.google.com/github/Kanika018/Machine-Learning1/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy

In [0]:
import numpy as np

In [0]:
a=np.array([2,7,1,99,4])

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([12,17,11,199,14])

In [0]:
a

array([ 2,  7,  1, 99,  4])

In [0]:
b

array([ 12,  17,  11, 199,  14])

In [0]:
a[0]

2

In [0]:
b[0]

12

In [0]:
a+b

array([ 14,  24,  12, 298,  18])

In [0]:
a+3

array([  5,  10,   4, 102,   7])

In [0]:
a*2

array([  4,  14,   2, 198,   8])

In [0]:
a**3

array([     8,    343,      1, 970299,     64])

In [0]:
vim mathops.py

SyntaxError: ignored

In [0]:
x=np.array([[2,5,8],[3,6,1]])

In [0]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
x[0]

array([2, 5, 8])

In [0]:
x[[0]]

array([[2, 5, 8]])

In [0]:
x[0][2]

8

In [0]:
x[1][0]

3

In [0]:
x+7

array([[ 9, 12, 15],
       [10, 13,  8]])

In [0]:
y=x***2

SyntaxError: ignored

In [0]:
y=x**3

In [0]:
y

array([[  8, 125, 512],
       [ 27, 216,   1]])

In [0]:
x*3

array([[ 6, 15, 24],
       [ 9, 18,  3]])

In [0]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
z=np.array([[2,7][1,3]])

TypeError: ignored

In [0]:
z=np.array([[2,7][1,3][3,4]])

TypeError: ignored

In [0]:
z=np.array([[2,1],[3,4],[5,7]])

In [0]:
z

array([[2, 1],
       [3, 4],
       [5, 7]])

In [0]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
x[0]

array([2, 5, 8])

In [0]:
z[0]

array([2, 1])

In [0]:
z[0:2]

array([[2, 1],
       [3, 4]])

In [0]:
z[0:]

array([[2, 1],
       [3, 4],
       [5, 7]])

In [0]:
z[0:,]

array([[2, 1],
       [3, 4],
       [5, 7]])

In [0]:
z=[0:,0]

SyntaxError: ignored

In [0]:
z

array([[2, 1],
       [3, 4],
       [5, 7]])

In [0]:
z[0:,0]

array([2, 3, 5])

In [0]:
z[0:2,2]

IndexError: ignored

In [0]:
z[0:2,1]

array([1, 4])

In [0]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
x[0:1,1]

array([5])

In [0]:
x[0:,1]

array([5, 6])

In [0]:
x[0:,0:2]

array([[2, 5],
       [3, 6]])

In [0]:
x[0:,[0,2]]

array([[2, 8],
       [3, 1]])

In [0]:
z[0,2]

IndexError: ignored

In [0]:
z[0,1]

1

In [0]:
z

array([[2, 1],
       [3, 4],
       [5, 7]])

In [0]:
z[[0,2]]

array([[2, 1],
       [5, 7]])

In [0]:
x.reshape(3,2)

array([[2, 5],
       [8, 3],
       [6, 1]])

In [0]:
x1=x.reshape(3,2)

In [0]:
x1

array([[2, 5],
       [8, 3],
       [6, 1]])

In [0]:
z

array([[2, 1],
       [3, 4],
       [5, 7]])

In [0]:
z[0,2,1]

IndexError: ignored

In [0]:
z[[0,2],1]

array([1, 7])

In [0]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [0]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [0]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [0]:
np.full((4,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [0]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '_distributor_init',


In [0]:
for i in dir(np):

SyntaxError: ignored

In [0]:
for i in dir(np):
  if 'zer' in i:
    print(i)

count_nonzero
flatnonzero
nonzero
trim_zeros
zeros
zeros_like


In [0]:
[for i in dir(np)]

SyntaxError: ignored

In [0]:
[i for i in dir(np)  if 'zer' in i]

['count_nonzero',
 'flatnonzero',
 'nonzero',
 'trim_zeros',
 'zeros',
 'zeros_like']

In [0]:
matplotlib

ImportError: ignored

In [0]:
import matplotlib

In [0]:
import numpy


In [0]:
a=np.array([1,2,3,4])

NameError: ignored

In [0]:
a

NameError: ignored

In [0]:
import numpy 


In [0]:
import numpy as np

In [0]:
a=np.array([1,2,3,4,5])

In [0]:
a

array([1, 2, 3, 4, 5])

In [0]:
b=np.array([5,6,7,2])

In [0]:
b

array([5, 6, 7, 2])